### Generated automatically from Makefile.in by configure.
all: linkedlistclass logfileclass errorlogclass
# ALL: default
##### User configurable options #####

SHELL       = /bin/sh
ARCH        = linux
CC          = gcc
CLINKER     = $(CC)
LD	    	= g++
AR          = ar crl
RANLIB      = ranlib
PROF_LIB    = -lmpe -lm
OPTFLAGS    = 


CFLAGS	  = -fPIC $(OPTFLAGS) 
CCFLAGS	  = $(CFLAGS)
EXECS	  = 

linkedlistclass: $(linkedlistclass)
	$(CC) $(CFLAGS) -c linkedlistclass.cpp 

logfileclass: $(logfileclass)
	$(CC) $(CFLAGS) -c logfileclass.cpp 

errorlogclass: $(errorlogclass)
	$(CC) $(CFLAGS) -c errorlogclass.cpp 

clean:
	/bin/rm -f *.o *~ 
